
server:
  port: 8082

spring:
  application:
    name: common-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://210.109.62.155:3306/common_db
    username: dev4
    password: dev4test

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: survey_platform
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:5010/realms/team_cloud/protocol/openid-connect/certs

keycloak:
  realm: team_cloud
  bearer-only: true
  ssl-required: external
  resource: team_cloud_client
  auth-server-url: http://localhost:5010/
  credentials:
    secret: AvgjtsAvqQUNfo9DemEpANjMt3YrAtbt

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

kakao:
  access:
    id: cffe7bbbeacc46cf910fcc5baa9caf16
    secret: vZdtSm7ZOAFxsXeDyP-DWMjgyOvT3TBXbgxT2uKEu_F3TzYcZwnUykfkfpc6VSmI44ndlQOYMIYWu98AxHD9iQ
  storage:
    account: cd8da9d86ee64a6d956451e8ab170bda
    bucketName: chatbot-file
